Export interface to fix compile error (#68)
In the build pipeline, when we compile the lambda we get an error: `error TS2304: Cannot find name 'FormDataAnswersObject'.`

This commit exports the interface so that the interface can be found during compiling.